  import type { Metadata } from "next";
  import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import Navbar from "@/components/Navbar";
  import ThemeToggle from "@/components/ThemeToggle";
  import { SmoothScrollProvider } from "@/components/ui/SmoothScrollProvider";


  const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html
  lang="en"
  className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
  suppressHydrationWarning
>
  <head>
    <script dangerouslySetInnerHTML={{
      __html: `
        const theme = localStorage.getItem('theme');
        if (theme === 'dark' || (!theme && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
          document.documentElement.classList.add('dark');
        }
      `
    }} />
  </head>
  <body className="min-h-full flex flex-col bg-[#f5f4ff] text-black dark:bg-black dark:text-white" suppressHydrationWarning>
    <SmoothScrollProvider>
      <div className="relative w-full flex justify-center items-center">
        <Navbar />
      </div>
      {children}
      <ThemeToggle />
   </SmoothScrollProvider>

  </body>
</html>
    );
  }
